# Default configuration values for the Kuma Helm chart

replicaCount: 1

image:
  repository: kong-docker-kuma-docker.bintray.io/kuma-cp
  tag: "2.1.0"
  pullPolicy: IfNotPresent

kumaDp:
  image:
    repository: kong-docker-kuma-docker.bintray.io/kuma-dp
    tag: "2.1.0"
    pullPolicy: IfNotPresent

kumaInit:
  image:
    repository: kong-docker-kuma-docker.bintray.io/kuma-init
    tag: "2.1.0"
    pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 5681
  annotations: {}

ingress:
  enabled: false
  path: /
  hosts:
    - host: kuma.local
      paths:
        - /
  tls: [] 

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}

mesh:
  name: default
  mtls:
    enabled: true

gateway:
  name: kuma-gateway
  namespace: kuma-system
  network:
    address: 0.0.0.0
    port: 5681
  tags:
    service: kuma-gateway

dataplane:
  name: kuma-dataplane
  namespace: kuma-system
  mesh: default
  network:
    inbound:
      - port: 8080
        servicePort: 8080
        tags:
          service: demo-app
    outbound:
      - service: kuma-gateway
  tags:
    service: kuma-dataplane