# Default configuration values for the Kuma Helm chart

# Replica count for the Kuma control plane
replicaCount: 1

# Configuration for the Kuma control plane image
image:
  repository: docker.io/kumahq/kuma-cp
  tag: "2.7.1"
  pullPolicy: IfNotPresent

# Command and arguments for the control plane container
controlPlane:
  command: ["kuma-cp"]
  args: ["run"]

# Configuration for the Kuma data plane image
kumaDp:
  image:
    repository: docker.io/kumahq/kuma-dp
    tag: "2.7.1"
    pullPolicy: IfNotPresent

# Configuration for the Kuma init container image
kumaInit:
  image:
    repository: docker.io/kumahq/kuma-init
    tag: "2.7.1"
    pullPolicy: IfNotPresent

# Service configuration for the Kuma control plane
service:
  enabled: true
  type: ClusterIP
  port: 5681
  annotations: {}

# Ingress configuration for exposing Kuma externally
ingress:
  enabled: false
  path: /
  hosts:
    - host: kuma.local
      paths:
        - /
  tls: []

# Resource requests and limits for the Kuma control plane
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Mesh configuration
mesh:
  name: default
  mtls:
    enabled: true

# Gateway configuration
gateway:
  name: kuma-gateway
  namespace: kuma-system
  network:
    address: 0.0.0.0
    port: 5681
  tags:
    service: kuma-gateway

# Data plane configuration
dataplane:
  name: kuma-dataplane
  namespace: kuma-system
  mesh: default
  network:
    inbound:
      - port: 8080
        servicePort: 8080
        tags:
          service: demo-app
    outbound:
      - service: kuma-gateway
  tags:
    service: kuma-dataplane