apiVersion: kuma.io/v1alpha1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  tags:
    service: {{ .Values.gateway.tags.service }}
  conf:
    listeners:
      - port: {{ .Values.gateway.network.port }}
        protocol: http