apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuma-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: kuma.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuma-control-plane
                port:
                  number: 5681
  tls:
    - hosts:
        - kuma.local
      secretName: kuma-tls-secret