apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kuma-system
  name: kuma-control-plane-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]