apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kuma-system
  name: kuma-control-plane-rolebinding
subjects:
  - kind: ServiceAccount
    name: kuma-control-plane
    namespace: kuma-system
roleRef:
  kind: Role
  name: kuma-control-plane-role
  apiGroup: rbac.authorization.k8s.io