# filepath: /workspaces/kind/kuma-repo/argocd/kuma-argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kumahq.github.io/charts
    targetRevision: 2.7.1 # Cambia esto a la versión de Kuma que deseas instalar
    chart: kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true