# filepath: /workspaces/kind/kuma-repo/argocd/kuma-argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
spec:
  project: poc-1
  source:
    repoURL: https://github.com/JaimeHenaoChallange/kuma-repo.git
    targetRevision: main # Cambia esto a la rama que deseas usar
    path: helm-charts/kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true